defmodule ExGitEngine.PackfileTest do
  use ExUnit.Case, async: true

  alias ExGitEngine.Packfile

  defp pack_with(version, count, extra \\ <<>>) do
    "PACK" <> <<version::32, count::32>> <> extra
  end

  describe "parse_header/1" do
    test "reads version and count from PACK-prefixed binary" do
      pack = pack_with(2, 5, :binary.copy(<<0>>, 20))
      assert {2, 5} = Packfile.parse_header(pack)
    end

    test "reads version and count from raw header (no PACK prefix)" do
      raw = <<2::32, 7::32>> <> :binary.copy(<<0>>, 20)
      assert {2, 7} = Packfile.parse_header(raw)
    end

    test "count zero is valid" do
      pack = pack_with(2, 0, :binary.copy(<<0>>, 20))
      assert {2, 0} = Packfile.parse_header(pack)
    end
  end

  describe "parse/1" do
    test "returns empty pack for 0-object packfile" do
      checksum = :crypto.strong_rand_bytes(20)
      pack = pack_with(2, 0, checksum)
      assert {:pack, []} = Packfile.parse(pack)
    end

    test "returns buffer when object data is entirely absent" do
      # Header claims 1 object but there is no object data after the header
      pack = pack_with(2, 1)
      assert {:buffer, [], {0, 1, ""}} = Packfile.parse(pack)
    end

    test "returns buffer when object data is incomplete (only size-header bytes)" do
      # 0b10110001 = MSB set → more size bytes follow; object body not present
      pack = pack_with(2, 1, <<0b10110001>>)
      assert {:buffer, [], {0, 1, _rest}} = Packfile.parse(pack)
    end
  end

  describe "parse/2 with iterator" do
    test "accepts iodata list and converts to binary" do
      checksum = :crypto.strong_rand_bytes(20)
      iodata = ["PACK", <<2::32>>, <<0::32>>, checksum]
      assert {:pack, []} = Packfile.parse(iodata, {0, 0, ""})
    end

    test "{0, 0, \"\"} iterator delegates to parse/1" do
      checksum = :crypto.strong_rand_bytes(20)
      pack = pack_with(2, 0, checksum)
      assert {:pack, []} = Packfile.parse(pack, {0, 0, ""})
    end

    test "resumes parse with more data appended to buffered rest" do
      {:buffer, [], {0, 1, ""} = iter} = Packfile.parse(pack_with(2, 1))
      # Append a few more bytes — still not enough for a full valid object
      result = Packfile.parse(<<0b10000001, 0b00000000>>, iter)
      assert match?({:buffer, _, _}, result) or match?({:pack, _}, result)
    end
  end

  describe "parse/1 integration with real packfile" do
    setup do
      path = Path.join(System.tmp_dir(), "ex_git_engine-packfile-#{:erlang.unique_integer()}")
      File.mkdir_p!(path)

      cmd = fn args -> System.cmd("git", ["-C", path | args], stderr_to_stdout: true) end
      cmd.(["init"])
      cmd.(["config", "user.email", "t@t.com"])
      cmd.(["config", "user.name", "T"])
      File.write!(Path.join(path, "hello.txt"), "hello\n")
      cmd.(["add", "."])
      cmd.(["commit", "-m", "init"])

      {:ok, agent} = ExGitEngine.GitAgent.start_link(path)

      on_exit(fn ->
        if Process.alive?(agent), do: GenServer.stop(agent)
        File.rm_rf!(path)
      end)

      %{agent: agent}
    end

    test "parses a real packfile generated by pack_create", %{agent: agent} do
      {:ok, ref} = ExGitEngine.GitAgent.branch(agent, "main")
      {:ok, commit} = ExGitEngine.GitAgent.peel(agent, ref)
      {:ok, pack} = ExGitEngine.GitAgent.pack_create(agent, [commit.oid])

      assert is_binary(pack)
      assert binary_part(pack, 0, 4) == "PACK"
      assert match?({:pack, [_ | _]}, Packfile.parse(pack))
    end

    test "parse/2 with split pack data exercises incremental path", %{agent: agent} do
      {:ok, ref} = ExGitEngine.GitAgent.branch(agent, "main")
      {:ok, commit} = ExGitEngine.GitAgent.peel(agent, ref)
      {:ok, pack} = ExGitEngine.GitAgent.pack_create(agent, [commit.oid])

      # Truncate to just the 12-byte header → buffer state
      header = binary_part(pack, 0, 12)
      rest = binary_part(pack, 12, byte_size(pack) - 12)

      {:buffer, [], iter} = Packfile.parse(header)

      # Feed the rest — should complete the pack
      result = Packfile.parse(rest, iter)
      assert match?({:pack, [_ | _]}, result) or match?({:buffer, _, _}, result)
    end
  end
end
